name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/my-app:latest

    - name: Run Container (Local Verification)
      run: |
        docker run -d -p 2000:2000 --name docker-container ${{ secrets.DOCKER_USERNAME }}/my-app:latest
        sleep 10
        curl -f http://localhost:3000 || (echo "App did not respond!" && exit 1)
        docker stop test-container
        docker rm test-container
